[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  # If you actually use NASA APOD, set this in Netlify UI > Environment variables
  # EXPO_PUBLIC_NASA_API_KEY = "YOUR_KEY_HERE"

# ---- Security headers (CSP) ----
[[headers]]
  for = "/*"
  [headers.values]
    # Keep this tight; only add what you truly use.
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://api.stripe.com https://*.supabase.co https://translation.googleapis.com https://api.nasa.gov https://ingesteer.services-prod.nsvcs.net;
      img-src 'self' data: blob: https://apod.nasa.gov https://img.youtube.com https://i.ytimg.com;
      media-src 'self' https://apod.nasa.gov https://www.youtube.com https://youtube.com;
      frame-src 'self' https://www.youtube.com https://youtube.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
    """

# (Optional) Cache static assets longer
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
